//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCareTPADAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurer()
        {
            this.Hospitals = new HashSet<Hospital>();
        }
    
        public int InsureId { get; set; }
        public string InsurerName { get; set; }
        public Nullable<int> RegistrationNo { get; set; }
        public string HeadOffice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospital> Hospitals { get; set; }
    }
}
